echoでの変換
yama-hiroki/studylesson pull request #5
Opened 2023-06-23 05:32 UTC by yama-hiroki

## POSTとGetのAPIサーバーをEchoに置き換える

- 参考にした記事
[公式ドキュメント](https://echo.labstack.com/guide/http_server/)
[echoを使ったAPIサーバーの構築](https://zenn.dev/def_yuisato/articles/echo-get-started)

2023-06-26 03:51 UTC, ln-saito-ry requested changes

2023-06-26 03:51 UTC, ln-saito-ry commented on main.go
> +	return c.String(http.StatusOK, string(data))
jsonで返したいので、c.Jsonを使用してください！

2023-06-26 03:51 UTC, ln-saito-ry commented on main.go
> +	return c.String(http.StatusOK, buf.String())
こちらもc.Jsonでお願いします！

2023-06-26 05:59 UTC, ln-saito-ry approved these changes

2023-06-26 06:05 UTC, ln-saito-ry requested changes

2023-06-26 06:05 UTC, ln-saito-ry commented on main.go
> +	say, err := io.ReadAll(c.Request().Body)
echoのBindとValidateを使う書き方に変更してみてください！
nameのバリデーションはrequiredでお願いします

2023-06-26 06:16 UTC, ln-saito-ry commented on main.go
> +	say, err := io.ReadAll(c.Request().Body)
賃貸プロジェクトはCustomValidator, CustomBinderを使用して色々カスタマイズしていますが、これらのcustomは使わず、最小限でOKです！

2023-06-26 06:41 UTC, ln-saito-ry commented on main.go
> +	say, err := io.ReadAll(c.Request().Body)
すみません、validatorはCustomValidatorが必要でした！
以下を参考にお願いします！
https://echo.labstack.com/guide/request/#validate-data

2023-06-26 08:12 UTC, yama-hiroki commented on main.go
> +	"github.com/go-playground/validator"
10行目では3つのエラーが起きています
Cannot resolve symbol 'github.com'
Cannot resolve symbol 'go-playground'
"github.com/go-playground/validator"

2023-06-26 08:12 UTC, yama-hiroki commented on main.go
> +}
23行目の.Validateの部分が赤くなって以下のエラーを起こしています
Unresolved type 'Validate'

2023-06-26 08:12 UTC, yama-hiroki commented on main.go
>  	e.Use(middleware.Logger())
29行目が以下のエラーを起こしています
Unresolved reference 'New'

2023-06-26 08:12 UTC, yama-hiroki commented on main.go
> +}
46行目と47行目の部分で以下のエラーを起こしています。
Unresolved reference 'Struct'　46行目
Unresolved reference 'Error'　47行目

2023-06-26 08:30 UTC, ln-saito-ry reviewed
ターミナルを開いて`go get "github.com/go-playground/validator"`と打つと解決する気がします！
上記go-playground/validator含め、外部パッケージをimportする場合、ローカルにライブラリのコードを落としてきて使用します。

1. `go get ライブラリのURL`でローカルにコードを落とす
2. importにURLを書いて使用する

1と2は逆でも問題ないですが、恐らく1を実行していないのではないでしょうか？
ちなみに、落としたコードは`~/go/バージョン/pkg/mod`配下に格納されます（今回は`ls ~/go/1.20/pkg/mod/github.com`と打つとgo-playgroundがあるかと）

それと、go.modの3行目のgoのバージョンは、賃貸プロジェクト合わせで1.19でお願いします！

ちなみに、go getの代わりに`go mod tidy`という便利なコマンドも使えます。
これは以下の処理をしてくれるので、go getの代わりにこちらでもOKです
- importに記載されているもののローカルに落としていないコードを落とす
- 使用していないimportを削除する

2023-06-26 09:33 UTC, yama-hiroki commented
現状としましてはvalidateの部分で失敗して上手くいっていない状況です。主に57行目のc.Validate()でValidate関数を参照にすることで45-50行目のValidateの関数の処理を行った際に、46行目のif文の処理でerrにはerrorが入っているため、47行目でecho.NewHTTPError(http.StatusBadRequest, err.Error())を返すことによりエラーが出ています。

2023-06-26 10:35 UTC, ln-saito-ry commented on main.go
> +	if err = c.Bind(&say); err != nil {
公式に書いてある説明を読むと、Bindの使い方が間違っているようです
https://echo.labstack.com/guide/binding/#struct-tag-binding

2023-06-27 02:14 UTC, ln-saito-ry approved these changes

2023-06-27 02:14 UTC, ln-saito-ry commented on main.go
>  	jsonBytes := say
53-59行目の処理は不要になります！
※c.Bind内で内部的にjson.Unmarshalし、input構造体に詰め替えるという同じ処理をしているため

つまり、ここでは同じ処理を2回実行してしまっていることになります。

2023-06-27 03:12 UTC, merged